### PR TITLE
Folder cleanup

### PR DESCRIPTION
**Pull request by kkarrwrites**
Hi all! So I did a little cleanup this morning of our files, which I hope is okay, but I was having some problems running our code from last night. Basically, I did the following:

1.) Deleted the client/node_modules folder. (This is enormous!)
2.) Cleaned up the README.md in the root. (It had boilerplate text from the React app. For now, it just contains our title.)
3.) I made a minor change to the client/.gitignore. (I deleted the / in front of the node_modules just like Michael did in the server/.gitignore.)
4.) I deleted the reportWebVitals.js and setupTest.js files in the client folder. (These are just boilerplate files that get installed when you create a React app, and we don't need them.)
5.) I updated the package.json file in the root. (It contained React dependencies, which only need to be in the client folder's package.json. I added concurrently, which we'll need to get our server and client folders working together.)
6.) I updated the package.json file in the client folder. (There were some issues with the React app version number and some other things that was making it so that it wouldn't run for me locally. Hopefully these changes are okay. I can run React now without any errors, so hopefully it works for everyone else too!)

Perhaps we can review this tonight before we get too far into making anymore new change? Thanks all!

### CODE REVIEW

**Comment by kkarrwrites** [comment]
So...ignore a commit comment I made saying that I removed the apollo/client, graphql, and jwt-decode dependencies from the client json file. That was a mistake! I put them back in a later commit. We need those dependencies in the client folder!

**Review by Reptartheman — COMMENTED** [review]
Rad!

**Review by TioMeko — APPROVED** [review]
jeff said good

**Comment by Reptartheman** [comment]
I comment nicely

**Pull request merged**
